FLASK_PORT = 5000

USER_ID_ENTERED = "USER_ID_ENTERED"
USER_ID = "USER_ID"
LOGGED_IN = "LOGGED_IN"
CURRENT_ANNOTATION_EXAMPLE = "CURRENT_ANNOTATION_EXAMPLE"
COMPLETED_ANNOTATIONS = "COMPLETED_ANNOTATIONS"
TOKEN_CODE = "TOKEN_CODE"

HTTP_UNAUTHORIZED_403 = 403